'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class lu_Performer
    Public Property id As Integer
    Public Property name As String
    Public Property aliases As String
    Public Property gender As String
    Public Property excluded As Nullable(Of Byte)
    Public Property url As String
    Public Property lastUpdate As Nullable(Of Date)

    Public Overridable Property Scene_Data18_Performers As ICollection(Of Scene_Data18_Performers) = New HashSet(Of Scene_Data18_Performers)
    Public Overridable Property Scene_Performers As ICollection(Of Scene_Performers) = New HashSet(Of Scene_Performers)

End Class
