'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class lu_QuarterType
    Public Property id As Integer
    Public Property code As String
    Public Property shortDescription As String
    Public Property longDescription As String
    Public Property imageFileName As String
    Public Property lastUpdate As Nullable(Of Date)

    Public Overridable Property Quarters As ICollection(Of Quarter) = New HashSet(Of Quarter)

End Class
