'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure
Imports System.Data.Entity.Core.Objects
Imports System.Linq

Partial Public Class MediaContext
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=MediaContext")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property PlaylistMusics() As DbSet(Of PlaylistMusic)

    Public Overridable Function sec_Select_PlaylistMusic() As ObjectResult(Of sec_Select_PlaylistMusic_Result)
        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of sec_Select_PlaylistMusic_Result)("sec_Select_PlaylistMusic")
    End Function

End Class
