'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class NationalSite
    Public Property id As Integer
    Public Property locationId As Integer
    Public Property containingLocationId As Integer
    Public Property lastUpdate As Nullable(Of Date)

    Public Overridable Property Location As Location
    Public Overridable Property Location1 As Location

End Class
