'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Scene_Categories
    Public Property id As Integer
    Public Property sceneId As Integer
    Public Property categoryId As Integer
    Public Property lastUpdate As Nullable(Of Date)

    Public Overridable Property lu_Category As lu_Category
    Public Overridable Property Scene As Scene

End Class
