'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Scene_Data18
    Public Property id As Integer
    Public Property siteId As Integer
    Public Property data18Id As Nullable(Of Integer)
    Public Property title As String
    Public Property releaseDate As Nullable(Of Date)
    Public Property url As String
    Public Property story As String
    Public Property lastUpdate As Nullable(Of Date)

    Public Overridable Property Scene_Data18_Categories As ICollection(Of Scene_Data18_Categories) = New HashSet(Of Scene_Data18_Categories)
    Public Overridable Property Scene_Data18_Performers As ICollection(Of Scene_Data18_Performers) = New HashSet(Of Scene_Data18_Performers)
    Public Overridable Property Site As Site

End Class
