'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Scene
    Public Property id As Integer
    Public Property siteId As Integer
    Public Property sceneId As Nullable(Of Integer)
    Public Property title As String
    Public Property releaseDate As Nullable(Of Date)
    Public Property url As String
    Public Property description As String
    Public Property likes As Nullable(Of Integer)
    Public Property dislikes As Nullable(Of Integer)
    Public Property views As Nullable(Of Integer)
    Public Property rating As Nullable(Of Decimal)
    Public Property lastUpdate As Nullable(Of Date)

    Public Overridable Property Scene_Categories As ICollection(Of Scene_Categories) = New HashSet(Of Scene_Categories)
    Public Overridable Property Scene_Performers As ICollection(Of Scene_Performers) = New HashSet(Of Scene_Performers)
    Public Overridable Property Site As Site

End Class
